import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/core';
import '@angular/common';
import '@angular/forms';
import '@angular/http';
import '@angular/router';
// RxJS
import 'rxjs';
// CSS
import 'font-awesome/css/font-awesome.css';
import 'primeng/resources/themes/bootstrap/theme.css';
import 'primeng/resources/primeng.css';